// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoLzBGiOVwvAs7-Xwv2L2m0jpc6i2l8wY',
    appId: '1:187096973237:web:10b0f3a70ecc9fd9a823fc',
    messagingSenderId: '187096973237',
    projectId: 'moapp-proejct',
    authDomain: 'moapp-proejct.firebaseapp.com',
    storageBucket: 'moapp-proejct.appspot.com',
    measurementId: 'G-4TCC9YSB33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbhoEodCNyJvTxmbwvtSUQYzh5NY_Q6Q',
    appId: '1:187096973237:android:dd01947878a8db30a823fc',
    messagingSenderId: '187096973237',
    projectId: 'moapp-proejct',
    storageBucket: 'moapp-proejct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7i-60NHD3JGmdJF4v1ouO--b_gPVjl-0',
    appId: '1:187096973237:ios:df30f88cf05c80f2a823fc',
    messagingSenderId: '187096973237',
    projectId: 'moapp-proejct',
    storageBucket: 'moapp-proejct.appspot.com',
    iosBundleId: 'com.example.moappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7i-60NHD3JGmdJF4v1ouO--b_gPVjl-0',
    appId: '1:187096973237:ios:63e4e8a096cb0201a823fc',
    messagingSenderId: '187096973237',
    projectId: 'moapp-proejct',
    storageBucket: 'moapp-proejct.appspot.com',
    iosBundleId: 'com.example.moappProject.RunnerTests',
  );
}
